# Generated by Django 3.1.7 on 2021-03-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210304_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blocked',
        ),
    ]
