# Generated by Django 3.1.7 on 2021-06-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='none', upload_to='posts'),
        ),
    ]
